### ISSUE TITLE
Lorenz Attractor IPython Notebook is deprecated

### ISSUE THREAD

**Issue by JunwenBai** [BouchardLab/DynamicalComponentsAnalysis#42]
Dear Authors,
I was reading lorenz_fig.ipynb in notebooks folder. But there are too many bugs. For example, `ComplexityComponentAnalysis` is not imported at all. Also, even correcting the bugs cannot give desired figs as reported in the paper. Could you update the ipython notebook?
Best

**Comment by JesseLivezey** [comment]
You should be able to run the Fig1 notebook now.
