### ISSUE TITLE
Could you share sabes dataset?

### ISSUE THREAD

**Issue by JunwenBai** [BouchardLab/DynamicalComponentsAnalysis#44]
Dear authors,
Since a lot of notebooks use sabes dataset ("/Projects/ComplexityComponentsAnalysis/data/sabes/indy_20160627_01.mat"), do you mind sharing the link to the dataset?
Best

**Comment by JesseLivezey** [comment]
You can download indy_20160627_01.mat from 
https://zenodo.org/record/583331

**Comment by JesseLivezey** [comment]
I added links to all of the datasets in the README

**Comment by JunwenBai** [comment]
That's awesome! Thx!

**Comment by JunwenBai** [comment]
> I added links to all of the datasets in the README

Hi, Jesse,
Do you mind further clarifying which sub_19.csv did you use? There are 15 sub-folders in A_DeviceMotion_data.zip, and each of them has a sub_19.csv. >_<
Best

**Comment by JunwenBai** [comment]
Besides, may I further ask which ipynb or code could generate real_data.npz? I notice that a lot of plotting codes need that npz file, but I don't see a code generating it.

**Comment by JesseLivezey** [comment]
It was the one in std_6.
